### ISSUE TITLE
lintcode user login not working

### ISSUE THREAD

**Issue by armishra** [skygragon/leetcode-cli-plugins#14]
The current [URL_LOGIN](https://github.com/skygragon/leetcode-cli-plugins/blob/master/plugins/lintcode.js#L32
) here may be wrong. I tried sending http requests to this but I think it needs to be changed.

**Comment by skygragon** [comment]
@armishra please try the latest lintcode plugin

**Comment by armishra** [comment]
Works now. Thanks for the patch!
