### ISSUE TITLE
[solution plugin] error showing solutions for 377

### ISSUE THREAD

**Issue by yefeiw** [skygragon/leetcode-cli-plugins#2]
[Problem screenshot]
![image](https://user-images.githubusercontent.com/3374560/29997591-fbab93da-8fcb-11e7-8d97-c6c4009d3d55.png)

I think this is an empty args error of some sort. 
I can try debugging on my own but I need some help as of where to start cracking this problem.
Using leetcode version 2.0.2.

**Comment by skygragon** [comment]
Thanks for reporting this. It seems leetcode.com used different logic to display solutions on page 
 for those newer problems. Will try to look into this later whenever possible from other busy work.

**Comment by skygragon** [comment]
@yefeiw please try the latest `solution.discuss` plugin (v=2017.12.21) to see if the issue is gone.
