### ISSUE TITLE
Cannot submit to github

### ISSUE THREAD

**Issue by niketkandya** [skygragon/leetcode-cli-plugins#24]
user@a01 ~/Code/leet % leetcode cfg plugins:github                                                               [0][17:45:06]
{
  "repo": "https://github.com/niketkandya/code.git",
  "token": "***"
}

user@a01 ~/Code/leet % leetcode submit 532.k-diff-pairs-in-an-array.cpp                                          [0][17:45:19]
  ✔ Accepted
  ✔ 72/72 cases passed (32 ms)
  ✔ Your runtime beats 67.03 % of cpp submissions
  ✘ {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}

user@a01 ~/Code/leet % git clone https://github.com/niketkandya/code.git                                         [0][17:45:41]
Cloning into 'code'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
user@a01 ~/Code/leet %

**Comment by skygragon** [comment]
try modify your "repo" in cfg like "https://github.com/niketkandya/code"?

**Comment by niketkandya** [comment]
That fixes it :)
