### ISSUE TITLE
leetcode session error when using lintcode plugin

### ISSUE THREAD

**Issue by cedricxie** [skygragon/leetcode-cli-plugins#25]
Hi @skygragon , 

Thanks for making this useful cli! I am using the latest version of leetcode-cli with lintcode plugin. However, when I try to do "leetcode session", it prompts "[ERROR] session expired, please login again [-1]". I am able to test and submit though. Let me know if more info is needed. Thank you.

Yuesong

**Comment by skygragon** [comment]
oh, sorry I don't have time to fully implement some features in lintcode, and `session` is surely one of them...

**Comment by cedricxie** [comment]
Thanks for the reply @skygragon.  I understand. Thanks again for making the cli tool !
