### ISSUE TITLE
github plugin error

### ISSUE THREAD

**Issue by zcmartian** [skygragon/leetcode-cli-plugins#27]
when i submit accepted code, it comes an error as follow:
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}

**Comment by zcmartian** [comment]
i have figured out that the "repo" config value should not be the repository url but the code base url instead.
for example:
if your repo is "https://github.com/xxx/leetcode-solutions.git", the base url is "https://github.com/xxx/leetcode-solutions", and you should set the plugin:github:repo the second one.

**Comment by zcmartian** [comment]
although it can auto commit your code into your repo in github, you cannot edit any commit message in the commit.

**Comment by dxsup** [comment]
I have encountered the same problem, and your solution works for me. Thanks!
