### ISSUE TITLE
[lintcode]Plugin not found

### ISSUE THREAD

**Issue by AlanKSH** [skygragon/leetcode-cli-plugins#3]
I want to install plugin lintcode
`leetcode plugin -i lintcode.js`
but error occurs:
Plugin not found!

Do I enter the right command? Could you please help me fix this, thanks.

**Comment by harrifeng** [comment]
I faced the same problem

**Comment by skygragon** [comment]
Sorry for the misleading guide, the plugin install only accept a local path to the plugin js file, which means you should download the js first and feed leetcode with the local path.

Will update the guide and also enhance the plugin command to fetch the plugin js from github directly.

**Comment by skygragon** [comment]
@AlanKSH @harrifeng please try the latest commit on leetcode, now it supports installing the plugin from Github directly.

```
$ npm install -g skygragon/leetcode-cli
$ leetcode plugin -i lintcode
```

**Comment by skygragon** [comment]
leetcode 2.0.3 is release with this enhancement.
