### ISSUE TITLE
github plugin fail

### ISSUE THREAD

**Issue by travisjiang** [skygragon/leetcode-cli-plugins#4]
when using github plugin：
leetcode submit 1.two-sum.py

it shows:
```
/usr/local/bin/leetcode submit <filename>

Options:
  --help  Show help                                                    [boolean]

Parameter 'url' must be a string, not undefined
```

I found its wrong in github.js

**Comment by skygragon** [comment]
could you paste your config file? e.g. ~/.lcconfig

**Comment by yunweiyuan** [comment]
I suffer the same issue. I failed to locate the path to lcconfig. There isn’t a file named such in my whole computer. But leetcode config -a works properly. I’m using it on my Odroid-xu4, a raspberry pi like computer. FYI.
leetcode config -a outputs:
{
  "autologin": {
    "enable": true
  },
  "code": {
    "editor": "vim",
    "lang": "java"
  },
  "color": {
    "enable": true,
    "theme": "default"
  },
  "icon": {
    "theme": ""
  },
  "network": {
    "concurrency": 10
  },
  "plugins": {
    "github": {
      "repo": "https://github.com/***/***.git",
      "token": "******"
    }
  }
}

**Comment by skygragon** [comment]
@travisjiang @yunweiyuan please try to re-install github plugin to see if recent fixes works for you.

**Comment by skygragon** [comment]
@yunweiyuan btw, you can find the new config at ~/.lc/config.json

**Comment by yunweiyuan** [comment]
@skygragon Thanks for your quick fix! The submit works but fail to commit to github.
output as following:
  ```
✔ Accepted
  ✔ 13/13 cases passed (15 ms)
  ✔ Your runtime beats 44.05 % of java submissions
  ✘ {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

**Comment by skygragon** [comment]
@yunweiyuan it seems your configured a non-exist repo url?

**Comment by yunweiyuan** [comment]
@skygragon Sorry, my apology. It does work. Appreciate for your great contribution!
