### ISSUE TITLE
[cookie.chrome] Crash when not using default chrome profile

### ISSUE THREAD

**Issue by ilaskaev** [skygragon/leetcode-cli-plugins#7]
Chrome provides support for profiles. When you do not have a `Default` profile or are using a profile that is not the `Default` profile, the `Cookies` db file will either be not found (causing a crash) or you won't be able to retrieve the leetcode cookie.

The currently active profile can be seen in chrome using `chrome://version/`.

**Comment by skygragon** [comment]
@ilaskaev could you try the latest plugin to see if it meets your need?

**Comment by ilaskaev** [comment]
@skygragon All works well now. Thank you.
