### ISSUE TITLE
[github] failed to submit commit to github repo.

### ISSUE THREAD

**Issue by skygragon** [skygragon/leetcode-cli-plugins#8]
the "github" package has been renamed to "@octokit/rest"

```
Error: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
```

see https://github.com/octokit/rest.js/releases/tag/v14.0.0

**Comment by duyue6002** [comment]
same problem

**Comment by fakeYanss** [comment]
same

**Comment by skygragon** [comment]
@duyue6002 @fakeYanss please try reinstall github plugin with the latest fix?

**Comment by fakeYanss** [comment]
what is "github plugin"? Is it a plugin name?

**Comment by skygragon** [comment]
@fakeYanss have you got 'github' plugin finally work?

**Comment by fakeYanss** [comment]
Yes, it works. And now the problem is when i want to `leetcode submit` in a python loop code, just like this:
```python
def submit():
    for file in os.listdir('.'):
        if not re.match("^[0-9]", file): # all submission file name are start with "0-9"
            continue
        os.system('leetcode submit ' + file)
        # time.sleep(20)
```
it will reponse info like this:
```
  √ Accepted
  √ 20/20 cases passed (9 ms)
  √ Your runtime beats 61.78 % of java submissions
  √ Committed to https://github.com/fakeYanss/leetcode
  √ Accepted
  √ 476/476 cases passed (5 ms)
  √ Your runtime beats 97.56 % of java submissions
  √ Committed to https://github.com/fakeYanss/leetcode
[ERROR] http error [429]
[ERROR] http error [429]
[ERROR] http error [429]
...
```
finally i make the program sleep 20s every time in loop, but it is low efficient. Did you have such a problem?

**Comment by skygragon** [comment]
429 error usually means you have sent too many requests to server within a given time window. In you case I guess leetcode.com is refusing to run your further submissions if you submit too fast. You have to slow down since leetcode.com won't approve that speed.

Or you could modify github.js to temporarily bypass the leetcode.com submission logic and send file to GitHub directly, while I think you will still get similar error since GitHub itself has rate limit as well: https://developer.github.com/v3/#rate-limiting

**Comment by fakeYanss** [comment]
ok, thank for your response. Maybe i should concentrate on the original purpose of solve algorithm problems. And leetcode-cli is a very nice tool. It can provide mostly functions i have expectd. Thany you very much. The last question, do you live in Shanghai now?
